### ISSUE TITLE
【一般】（用户门户）登录页-租户申请注册页面，租户名称 项，没有做限制，输入超长字符，点击“提交”，报500

### ISSUE THREAD

**Issue by chenhy6** [AIPaaS/PaaS-FE-SYS#31]
环境：win7
浏览器：火狐、Chrome
测试环境：http://10.1.245.247:16004/paas-web
步骤：
1.进入登录页
2.进入 租户申请注册 页面，租户名称 项，没有做限制，输入超长字符，点击“提交”，报500：HTTP ERROR 500Problem accessing /paas-wsso/regsucc.jsp. Reason: URLDecoder: Illegal hex characters in escape (%) pattern - For input string: "??"Caused by:
java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern - For input string: "??"
	at java.net.URLDecoder.decode(URLDecoder.java:192)
	at com.binary.core.http.URLResolver.decode(URLResolver.java:85)
	at com.binary.core.http.URLResolver.decode(URLResolver.java:70)
	at org.apache.jsp.regsucc_jsp._jspService(org.apache.jsp.regsucc_jsp:62)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:109)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:389)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:486)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:380)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1221)
	at com.binary.framework.web.filter.LoginValidateFilter.doFilter(LoginValidateFilter.java:223)
	at com.binary.sso.server.web.SsoLoginValidateFilter.doFilter(SsoLoginValidateFilter.java:73)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212)
	at com.binary.framework.web.filter.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:28)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:399)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:450)
	at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:928)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:410)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)

**Comment by mapl-pisces** [comment]
1）、提测的功能说明：注册时租户名称添加长度限制
2）、代码分支说明：https://github.com/AIPaaS/PaaS-FE-SSO.git    develop
3）、配置信息说明：无
4）、数据库说明：无
5）、是否有特殊的第三方软件安装：无

**Comment by chenhy6** [comment]
验证通过
